[general]
import = ["~/.config/alacritty/current_theme.toml"]
# import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[window]
padding = { x = 15, y = 0 }
opacity = 0.90

[scrolling]
history = 10000
multiplier = 3

[font]
size = 19.0
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
# family = "Terminess Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
# family = "Terminess Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
# family = "Terminess Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
# family = "Terminess Nerd Font Mono"
style = "Bold Italic"

[cursor]
blink_interval = 600
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[[keyboard.bindings]]
chars = " s \r"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control"

[terminal.shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/usr/bin/tmux"

[terminal]
