format = """
$username@$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$git_metrics\
$c\
$python\
$rust\
$golang\
$docker_context\
$nodejs\
$lua\
$java\
$haskell\
$fill\
$kubernetes\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " "

[username]
show_always = true
format = '\[[fab]($style)'
style_user = "#BD93F9"

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](#BD93F9): '
disabled = false

[directory]
format = '[$path]($style)\]'
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ï ½"
style = "bold #50fa7b"

# # Here is how you can shorten some long paths by text replacement
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[character]
success_symbol = "[â¯](bold #50fa7b)"
error_symbol = "[â¯](bold #ff5555)"

[cmd_duration]
disabled = false
format = '[â± $duration ]($style)'
style = "bold #f1fa8c"

# git section
[git_branch]
symbol = "ï˜"
format = "[ $symbol $branch]($style) "
style = "bold #ff79c6"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold #ff5555"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false


# virtualization section
[kubernetes]
format = '[ âˆ $context/$namespace](dimmed green)'
disabled = false
detect_files = ['k8s']
detect_folders = ['kube','k8s','helm','kustomize']
detect_extensions = ['j2','yaml','yml']

[docker_context]
symbol = "ïŒˆ "
format = '[$symbol $context ]($style) $path'

# languages section
[c]
symbol = "î˜ "
format = '[ $symbol ($version)]($style)'

[python]
symbol = "îˆµ "
# symbol = "ğŸ "
format = '[ $symbol($version)]($style)'

[rust]
symbol = "î¨ "
format = '[$symbol($version)]($style)'

[golang]
symbol = "î˜§ "
format = '[$symbol($version)]($style)'

[lua]
symbol = "î˜  "
format = '[$symbol($version)]($style)'

[haskell]
symbol = "î· "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
format = '[$symbol ($version) ]($style)'

[java]
symbol = "î‰– "
format = '[$symbol ($version) ]($style)'
